name: Pytest

on: [ push ]

jobs:
  run-tests:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install pytest coverage poetry
          poetry install
      - name: Run tests
        run: |
          poetry run pytest tests\